<a href="https://colab.research.google.com/github/abishkarKoirala/DataMiningLab/blob/main/Abishkar_lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 
a =np.array([1.,2.,3.])
a*2
a.dtype
c = np.zeros_like(a)
c

array([0., 0., 0.])

In [ ]:
b = np.zeros(4,int)
b

array([0, 0, 0, 0])

In [ ]:
import numpy as np
a = np.array([10,20,100,200,500])
b = np.array([3,4,5,6,7])
np.add(a, b)

array([ 13,  24, 105, 206, 507])

In [ ]:
np.subtract(a, b)

array([  7,  16,  95, 194, 493])

In [ ]:
np.multiply(a, b)

array([  30,   80,  500, 1200, 3500])

In [ ]:
np.divide(a,b)

array([ 3.33333333,  5.        , 20.        , 33.33333333, 71.42857143])

In [ ]:
np.remainder(a,b)

array([1, 0, 0, 2, 3])

In [ ]:
np.mod(a,b)

array([1, 0, 0, 2, 3])

In [ ]:
np.power(a,b)

array([               1000,              160000,         10000000000,
            64000000000000, 7812500000000000000])