In [1]:
print("hello world")

hello world


In [5]:
import numpy as np 
a =np.array([1.,2.,3.])
a*2
a.dtype
c = np.zeros_like(a)
c


array([0., 0., 0.])

In [4]:
b = np.zeros(4,int)
b

array([0, 0, 0, 0])

In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a+b

array([5, 7, 9])