<a href="https://colab.research.google.com/github/abishkarKoirala/DataMiningLab/blob/main/NumPyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

multidimensional array in numpy


In [ ]:
import numpy as np

In [ ]:
d=np.zeros((3,5))
print(d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
d.shape

(3, 5)

In [ ]:
s=(2,2)
np.zeros(s)

array([[0., 0.],
       [0., 0.]])

In [ ]:
a=np.array([2,3,5])
a*2

array([ 4,  6, 10])

In [ ]:
b=np.array([2,3,5])
a+b

array([ 4,  6, 10])

In [ ]:
a*b

array([ 4,  9, 25])

In [ ]:
c=np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [ ]:
c.shape

(2, 3)

In [ ]:
c.ndim

2

In [ ]:
c.dtype

dtype('int64')

In [ ]:
c.itemsize

8

In [ ]:
c.nbytes

48

note that the indexes start from 0

In [ ]:
c[1,-2]

5

In [ ]:
c[0,0]

1

In [ ]:
c[:,2]

array([3, 6])

In [ ]:
c[1,:]

array([4, 5, 6])

In [ ]:
x=np.array([80,90,100])
x.dtype

dtype('int64')

In [ ]:
x.nbytes

24

In [ ]:
x.itemsize

8